---

# VARIABLES TO EDIT
nomad_datacenter: "lab"
nomad_domain: "consul"
nomad_iface: eth1
nomad_network_interface: eth1
nomad_servers: ['server01.node.lab.consul:4647']
# CONSTANTS
nomad_consul_address: http://127.0.0.1:8500
nomad_vault_address: http://active.vault.service.lab.consul:8200
nomad_bind_address: "0.0.0.0"
nomad_use_consul: yes
nomad_vault_enabled: yes
nomad_options: {  'driver.raw_exec.enable': '1' }
nomad_network_speed: 10
nomad_bootstrap_expect: 1
nomad_docker_enable: yes
permanent: yes
nomad_ports_http: 4646
nomad_ports_rpc: 4647
nomad_ports_serf: 4648
