---

- hosts: service_traefik
  become: true
  become_user: root
  # ignore_errors: True
  # post_tasks:
  #   - name: Copy Traefik Config File
  #     template:
  #       src: ./playbooks/apps/traefik/traefik.toml
  #       dest: /etc/traefik.toml
  roles:
       - {role: olmax.traefik, tags: ['docker', 'nomad', 'traefik']}
